name = "HerbConstraints"
uuid = "1fa96474-3206-4513-b4fa-23913f296dfc"
authors = ["Jaap de Jong <jaapdejong15@gmail.com>"]
version = "0.1.1"

[deps]
HerbGrammar = "4ef9e186-2fe5-4b24-8de7-9f7291f24af7"
HerbCore = "2b23ba43-8213-43cb-b5ea-38c12b45bd45"

[compat]
HerbCore = "^0.2.0"
HerbGrammar = "^0.2.0"
julia = "^1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
